"""
Main Orchestrator Class
Complete workflow orchestrator integrating all components
"""
from typing import Dict, Any, Optional, List
import asyncio
import logging
from datetime import datetime

import sys
import os
sys.path.append(os.path.join(os.path.dirname(__file__), '..', '..', '..'))

# Import all the components we've created
from .state_management import StateManager, WorkflowState, NodeStatus
from .executor_factory import (
    NodeExecutorFactory, NodeConfig, ErrorStrategy, 
    RetryConfig, TimeoutConfig, NodeExecutionContext
)
from .conditional_routing import ConditionalRouter
from .parallel_coordinator import (
    ParallelExecutionCoordinator, MergeStrategy
)
from .circuit_breaker import CircuitBreakerRegistry, CircuitBreakerConfig
from .data_flow_system import DataFlowManager, CrossNodeDataBus
from .error_recovery import (
    CheckpointManager, FileCheckpointStorage,
    ErrorRecoveryManager, RecoveryStrategy, CheckpointType
)
from .scheduler import get_scheduler
from app.schemas.workflow_schema import (
    resolve_node_config, map_executor_output, VariableContext
)

logger = logging.getLogger(__name__)

class WorkflowOrchestrator:
    """
    Master orchestrator that integrates all components.
    """
    
    def __init__(
        self,
        api_keys: Optional[Dict[str, str]] = None,
        enable_checkpointing: bool = True,
        enable_circuit_breakers: bool = True,
        checkpoint_storage_dir: str = "./checkpoints"
    ):
        # Core components
        self.executor_factory = NodeExecutorFactory()
        self.conditional_router = ConditionalRouter()
        self.parallel_coordinator = ParallelExecutionCoordinator()
        self.data_bus = CrossNodeDataBus()
        
        # Circuit breakers
        self.enable_circuit_breakers = enable_circuit_breakers
        if enable_circuit_breakers:
            self.circuit_breaker_registry = CircuitBreakerRegistry()
        
        # Checkpointing
        self.enable_checkpointing = enable_checkpointing
        if enable_checkpointing:
            storage = FileCheckpointStorage(checkpoint_storage_dir)
            self.checkpoint_manager = CheckpointManager(
                storage,
                auto_checkpoint=True,
                checkpoint_interval_nodes=3
            )
            self.recovery_manager = ErrorRecoveryManager(
                self.checkpoint_manager
            )
        
        # Configuration
        self.api_keys = api_keys or {}
        
        # Register node executors
        self._register_node_types()
    
    def _register_node_types(self):
        """
        Auto-register node types from shared/nodes-metadata.json
        
        This eliminates manual type+alias registration. Each node's metadata
        declares its executor and aliases. This method loads metadata and:
        1. Dynamically imports executor classes
        2. Registers canonical type
        3. Registers all aliases to the same executor
        
        Benefits:
        - Single source of truth: src/workflows/*/metadata.ts
        - No duplicated registration lists
        - New nodes just need metadata + executor
        """
        import json
        import importlib
        from pathlib import Path
        
        # Load nodes metadata (generated by build script from metadata.ts files)
        metadata_path = Path(__file__).parent.parent.parent.parent / 'shared' / 'nodes-metadata.json'
        
        if not metadata_path.exists():
            logger.warning(f"nodes-metadata.json not found at {metadata_path}")
            logger.warning("Falling back to manual executor registration")
            self._register_node_types_legacy()
            return
        
        try:
            with open(metadata_path, 'r') as f:
                metadata = json.load(f)
        except Exception as e:
            logger.error(f"Failed to load nodes-metadata.json: {e}")
            logger.warning("Falling back to manual executor registration")
            self._register_node_types_legacy()
            return
        
        registered_count = 0
        failed_count = 0
        
        # Register each node from metadata
        for node_meta in metadata.get('nodes', []):
            canonical_type = node_meta.get('type')
            executor_class_name = node_meta.get('executor')
            aliases = node_meta.get('aliases', [])
            
            if not canonical_type or not executor_class_name:
                logger.warning(f"Skipping node: missing type or executor")
                failed_count += 1
                continue
            
            try:
                # Dynamically import executor class
                # Executor classes live in lib/workflow/langgraph/nodes/{category}/executors
                executor_class = self._load_executor_class(executor_class_name)
                
                if executor_class is None:
                    logger.warning(f"Could not load executor {executor_class_name}")
                    failed_count += 1
                    continue
                
                # Register canonical type
                self.executor_factory.register_executor(canonical_type, executor_class)
                logger.debug(f"Registered node type: {canonical_type}")
                
                # Register all aliases to the same executor
                for alias in aliases:
                    self.executor_factory.register_executor(alias, executor_class)
                    logger.debug(f"  └─ alias: {alias}")
                
                registered_count += 1
                
            except Exception as e:
                logger.error(f"Failed to register {canonical_type}: {e}")
                failed_count += 1
        
        logger.info(f"Node registration complete: {registered_count} succeeded, {failed_count} failed")
    
    def _load_executor_class(self, executor_class_name: str):
        """
        Dynamically load an executor class by name
        
        Tries multiple import paths:
        - lib.workflow.langgraph.nodes.{category}
        - lib.workflow.langgraph.nodes.logic (for common logic nodes)
        - lib.workflow.langgraph.nodes (fallback)
        """
        import importlib
        
        # List of modules to try in order
        import_candidates = [
            'lib.workflow.langgraph.nodes.logic',      # Delay, Stopper, etc.
            'lib.workflow.langgraph.nodes.triggers',   # Triggers
            'lib.workflow.langgraph.nodes.actions',    # Actions
            'lib.workflow.langgraph.nodes',             # Fallback
        ]
        
        for module_name in import_candidates:
            try:
                module = importlib.import_module(module_name)
                if hasattr(module, executor_class_name):
                    executor_class = getattr(module, executor_class_name)
                    logger.debug(f"Loaded {executor_class_name} from {module_name}")
                    return executor_class
            except ImportError:
                continue
        
        logger.warning(f"Could not load executor class: {executor_class_name}")
        return None
    
    def _register_node_types_legacy(self):
        """
        Legacy manual registration - used as fallback if nodes-metadata.json unavailable
        
        TODO: Remove this once metadata generation is reliable
        """
        from .nodes import (
            # Triggers
            ScheduleTriggerExecutor,
            WebhookTriggerExecutor,
            ManualTriggerExecutor,
            # Actions
            LoggerExecutor,
            HttpRequestExecutor,
            EmailExecutor,
            SlackExecutor,
            # Logic
            IfConditionExecutor,
            LoopExecutor,
            DelayExecutor,
            StopperExecutor,
            # AI/ML
            OpenAIExecutor,
            # Data
            JsonParseExecutor,
            DateFormatterExecutor,
        )
        
        # ===== TRIGGERS (3) =====
        # 1. Scheduling
        self.executor_factory.register_executor("Schedule", ScheduleTriggerExecutor)
        self.executor_factory.register_executor("Scheduling", ScheduleTriggerExecutor)
        self.executor_factory.register_executor("ScheduleTriggerNode", ScheduleTriggerExecutor)
        
        # 2. WebHook
        self.executor_factory.register_executor("Webhook", WebhookTriggerExecutor)
        self.executor_factory.register_executor("WebHook", WebhookTriggerExecutor)
        self.executor_factory.register_executor("WebhookTriggerNode", WebhookTriggerExecutor)
        
        # 3. Manual Trigger
        self.executor_factory.register_executor("Manual Trigger", ManualTriggerExecutor)
        self.executor_factory.register_executor("ManualTrigger", ManualTriggerExecutor)
        self.executor_factory.register_executor("OnClickExecuteTriggerNode", ManualTriggerExecutor)
        
        # ===== ACTIONS (5) =====
        # 4. Logger
        self.executor_factory.register_executor("Logger", LoggerExecutor)
        self.executor_factory.register_executor("LoggerNode", LoggerExecutor)
        
        # 5. HTTPRequest
        self.executor_factory.register_executor("HTTP Request", HttpRequestExecutor)
        self.executor_factory.register_executor("HTTPRequest", HttpRequestExecutor)
        self.executor_factory.register_executor("HttpRequest", HttpRequestExecutor)
        self.executor_factory.register_executor("HttpNode", HttpRequestExecutor)
        
        # 6. EmailSend
        self.executor_factory.register_executor("Send Email", EmailExecutor)
        self.executor_factory.register_executor("EmailSend", EmailExecutor)
        self.executor_factory.register_executor("Email", EmailExecutor)
        self.executor_factory.register_executor("EmailNode", EmailExecutor)
        
        # 7. Slack Message
        self.executor_factory.register_executor("Slack Message", SlackExecutor)
        self.executor_factory.register_executor("SlackMessage", SlackExecutor)
        self.executor_factory.register_executor("Slack", SlackExecutor)
        self.executor_factory.register_executor("SlackNode", SlackExecutor)
        
        # ===== LOGIC (4) =====
        # 9. Conditional
        self.executor_factory.register_executor("If Condition", IfConditionExecutor)
        self.executor_factory.register_executor("Conditional", IfConditionExecutor)
        self.executor_factory.register_executor("IfNode", IfConditionExecutor)
        
        # 10. Loop
        self.executor_factory.register_executor("Loop", LoopExecutor)
        self.executor_factory.register_executor("LoopNode", LoopExecutor)
        
        # 11. Delay
        self.executor_factory.register_executor("Delay", DelayExecutor)
        self.executor_factory.register_executor("DelayNode", DelayExecutor)
        
        # 12. Stopper (utility)
        self.executor_factory.register_executor("Stopper", StopperExecutor)
        self.executor_factory.register_executor("StopperNode", StopperExecutor)
        
        # ===== AI/ML (2) =====
        # 13. OpenAI
        self.executor_factory.register_executor("OpenAI GPT", OpenAIExecutor)
        self.executor_factory.register_executor("OpenAI", OpenAIExecutor)
        self.executor_factory.register_executor("OpenAINode", OpenAIExecutor)
        
        # ===== DATA (2) =====
        # 15. JSONParser
        self.executor_factory.register_executor("JSON Parse", JsonParseExecutor)
        self.executor_factory.register_executor("JSONParser", JsonParseExecutor)
        self.executor_factory.register_executor("JsonParse", JsonParseExecutor)
        self.executor_factory.register_executor("JsonParseNode", JsonParseExecutor)
        
        # 16. DataFormatter
        self.executor_factory.register_executor("Data Formatter", DateFormatterExecutor)
        self.executor_factory.register_executor("DataFormatter", DateFormatterExecutor)
        self.executor_factory.register_executor("DateFormatterNode", DateFormatterExecutor)
        
        logger.info(f"Registered {len(self.executor_factory.get_registered_types())} node types (legacy mode)")
    
    async def execute_workflow(
        self,
        workflow_data: Dict[str, Any],
        initial_input: Any = None
    ) -> Dict[str, Any]:
        """
        Execute a complete workflow.
        
        Args:
            workflow_data: Workflow definition from frontend
            initial_input: Initial input data
            
        Returns:
            Execution result with all node outputs and metadata
        """
        logger.info(f"Starting workflow execution: {workflow_data.get('id', 'unknown')}")
        
        # Create initial state
        state = StateManager.create_initial_state(
            workflow_id=workflow_data.get("id", "unknown"),
            initial_input=initial_input,
            config=workflow_data.get("config", {}),
            api_keys=self.api_keys
        )
        
        # Add workflow data to global config for nodes to access (needed for Schedule node)
        state["global_config"]["workflow_data"] = workflow_data
        state["global_config"]["workflow_id"] = workflow_data.get("id", "unknown")
        
        # Preserve scheduled execution flag if present
        if "global_config" in workflow_data and "_is_scheduled_execution" in workflow_data["global_config"]:
            state["global_config"]["_is_scheduled_execution"] = workflow_data["global_config"]["_is_scheduled_execution"]
        
        # Update workflow status
        state["workflow_status"] = "running"
        state["started_at"] = datetime.utcnow().isoformat()
        
        try:
            # Execute nodes based on connections
            nodes = workflow_data.get("nodes", [])
            connections = workflow_data.get("connections", [])
            
            logger.info(f"Workflow has {len(nodes)} nodes and {len(connections)} connections")
            if connections:
                logger.info(f"First connection keys: {list(connections[0].keys())}")
                logger.info(f"First connection: {connections[0]}")
            
            # Find start node (node with no incoming connections)
            all_target_nodes = {conn["targetNodeId"] for conn in connections}
            start_nodes = [node for node in nodes if node["id"] not in all_target_nodes]
            
            if not start_nodes:
                raise ValueError("No start node found in workflow")
            
            # Execute workflow starting from start node
            result = await self._execute_nodes(state, nodes, connections, start_nodes[0])
            
            # Update final state
            state["workflow_status"] = "completed"
            state["last_updated_at"] = datetime.utcnow().isoformat()
            
            # Generate summary
            summary = StateManager.get_execution_summary(state)
            
            return {
                "status": "success",
                "summary": summary,
                "final_output": state["current_data"],
                "node_logs": state["node_logs"],
                "execution_time_ms": state["execution_time_ms"]
            }
            
        except Exception as e:
            logger.error(f"Workflow execution failed: {str(e)}", exc_info=True)
            import traceback
            logger.error(f"Traceback: {traceback.format_exc()}")
            state["workflow_status"] = "failed"
            state["errors"].append(str(e))
            
            # NOTE: Temporarily disabled recovery for debugging - uncomment to re-enable
            # Attempt recovery if enabled
            # if self.enable_checkpointing and self.recovery_manager:
            #     recovered_state = await self.recovery_manager.handle_error(
            #         state, e, RecoveryStrategy.RESUME_FROM_CHECKPOINT
            #     )
            #     
            #     if recovered_state:
            #         # Retry from checkpoint
            #         logger.info("Retrying workflow execution from checkpoint")
            #         return await self.execute_workflow(workflow_data, initial_input)
            
            return {
                "status": "failed",
                "error": str(e),
                "partial_results": state.get("node_logs", [])
            }
    
    async def _execute_nodes(
        self,
        state: WorkflowState,
        nodes: List[Dict[str, Any]],
        connections: List[Dict[str, Any]],
        start_node: Dict[str, Any]
    ) -> Any:
        """
        Execute nodes in the workflow based on connections.
        
        Args:
            state: Current workflow state
            nodes: List of all nodes
            connections: List of connections between nodes
            start_node: Starting node
            
        Returns:
            Final output data
        """
        current_node = start_node
        current_data = state["current_data"]
        
        # Create a map of node ID to node for easy lookup
        node_map = {node["id"]: node for node in nodes}
        
        while current_node:
            node_id = current_node["id"]
            logger.info(f"Executing node: {node_id} ({current_node['type']})")
            
            # Mark node as visited
            state["visited_nodes"].append(node_id)
            state["current_node_id"] = node_id
            
            # Create checkpoint before execution if enabled
            if self.enable_checkpointing:
                await self.checkpoint_manager.create_checkpoint(
                    state, CheckpointType.NODE
                )
            
            try:
                # Execute the node
                node_output = await self._execute_single_node(
                    state, current_node, current_data
                )
                
                # After the start node executes, store trigger output for $trigger.x variables
                if current_node == start_node:
                    state["trigger_output"] = node_output
                
                # Update state with node result
                # Get node name with fallback: name -> type -> id
                node_name = (
                    current_node.get("name") or 
                    current_node.get("type") or 
                    node_id
                )
                log_entry = StateManager.update_node_log(
                    state,
                    node_id=node_id,
                    node_name=node_name,
                    node_type=current_node.get("type", "unknown"),
                    status=NodeStatus.SUCCESS,
                    output=node_output,
                    execution_time_ms=100.0  # Placeholder
                )
                state["node_logs"].append(log_entry)
                state["current_data"] = node_output
                
                # Store in data bus
                self.data_bus.set_node_output(node_id, node_output)
                
                # Find next node(s) based on connections
                next_connections = [
                    conn for conn in connections 
                    if conn["sourceNodeId"] == node_id
                ]
                
                if not next_connections:
                    # No more connections, workflow complete
                    logger.info(f"Workflow completed at node: {node_id}")
                    return node_output
                
                # Handle multiple connections (conditional routing)
                target_node_ids = self.conditional_router.route_connections(
                    next_connections, node_id, current_data, state["variables"]
                )
                
                if not target_node_ids:
                    # No routes matched, workflow ends here
                    logger.info(f"No routes matched from node: {node_id}")
                    return node_output
                
                # For simplicity, we'll follow the first matching route
                # In a more complex implementation, you might handle parallel execution
                next_node_id = target_node_ids[0]
                current_node = node_map.get(next_node_id)
                current_data = node_output
                
                if not current_node:
                    raise ValueError(f"Target node {next_node_id} not found")
                
            except Exception as e:
                logger.error(f"Error executing node {node_id}: {str(e)}")
                
                # Log the error
                # Get node name with fallback: name -> type -> id
                node_name = (
                    current_node.get("name") or 
                    current_node.get("type") or 
                    node_id
                )
                log_entry = StateManager.update_node_log(
                    state,
                    node_id=node_id,
                    node_name=node_name,
                    node_type=current_node.get("type", "unknown"),
                    status=NodeStatus.FAILED,
                    error=e,
                    execution_time_ms=0.0
                )
                state["node_logs"].append(log_entry)
                state["errors"].append(str(e))
                
                raise e
        
        return current_data
    
    async def _execute_single_node(
        self,
        state: WorkflowState,
        node: Dict[str, Any],
        input_data: Any
    ) -> Any:
        """
        Execute a single node.
        
        Args:
            state: Current workflow state
            node: Node definition
            input_data: Input data for the node
            
        Returns:
            Node output data
        """
        node_id = node["id"]
        node_type = node["type"]
        node_config = node.get("config", {})
        
        # Build variable resolution context from current execution state
        execution_context = VariableContext(
            trigger=state.get("trigger_output", {}),
            nodes=state.get("node_outputs", {}),
            variables=state.get("variables", {})
        )
        # Resolve all {{$node.x.y}} and {{$vars.x}} in config before execution
        resolved_config = resolve_node_config(node_config, execution_context)
        logger.info(f"Node {node_id} original config: {node_config}")
        logger.info(f"Node {node_id} resolved config: {resolved_config}")
        
        logger.info(f"Executing node {node_id} of type {node_type}")
        
        # Create node configuration
        config = NodeConfig(
            node_id=node_id,
            node_type=node_type,
            node_name=node.get("name", node_id),
            config=resolved_config,
            error_strategy=ErrorStrategy.FAIL_FAST,
            retry_config=RetryConfig(max_attempts=3),
            timeout_config=TimeoutConfig(execution_timeout_ms=120000)  # 2 minutes for debugging
        )
        
        # Create execution context
        # Get workflow data from state for Schedule node
        workflow_data = state.get("global_config", {}).get("workflow_data", {})
        context = NodeExecutionContext(
            execution_id=state["execution_id"],
            variables=state["variables"],
            api_keys=state["api_keys"],
            global_config={
                **state["global_config"],
                "workflow_data": workflow_data,
                "workflow_id": workflow_data.get("id", "unknown")
            }
        )
        
        # Use executor factory to execute the node
        try:
            logger.info(f"Calling executor for node {node_id} with resolved config: {resolved_config}")
            output, metrics = await self.executor_factory.execute_node(
                config, context, input_data
            )
            logger.info(f"Node {node_id} executor returned output: {output}")
            
            # Map executor return keys → metadata output IDs using outputMap
            output_map = node.get("outputMap", {})
            if output_map and isinstance(output, dict):
                logger.info(f"Mapping output with outputMap: {output_map}")
                output = map_executor_output(output, output_map)
                logger.info(f"Mapped output: {output}")
            # Store mapped output so downstream nodes can reference it
            state.setdefault("node_outputs", {})[node_id] = output
            
            # Log execution metrics
            logger.info(
                f"Node {node_id} executed successfully. "
                f"Time: {metrics.get('execution_time_ms', 0):.2f}ms"
            )
            
            return output
            
        except ValueError as e:
            # Configuration validation error
            error_msg = str(e)
            logger.error(f"Node {node_id} configuration error: {error_msg}")
            
            # Update state with error
            state["errors"].append(f"Node {node_id}: {error_msg}")
            
            raise ValueError(f"Node '{node_id}' ({node_type}) is not properly configured. {error_msg}")
        
        except Exception as e:
            # Other execution errors
            error_msg = str(e)
            logger.error(f"Node {node_id} execution error: {error_msg}")
            raise
    
    def register_node_executor(
        self,
        node_type: str,
        executor_class: Any,
        default_config: Optional[Dict[str, Any]] = None
    ):
        """
        Register a custom node executor.
        
        Args:
            node_type: Type identifier for the node
            executor_class: NodeExecutor subclass
            default_config: Default configuration for this node type
        """
        self.executor_factory.register_executor(
            node_type, executor_class, default_config
        )
        logger.info(f"Registered custom executor for node type: {node_type}")